import Head from "next/head";
import React, { useEffect } from "react";
// import Image from "next/image";
// import { Inter } from "next/font/google";
import Header from "../components/Header";
// import Navbar from "../components/Navbar";
import Link from "next/link";
import { useSession, signIn } from "next-auth/react";
// import image
import Ganesh from "../static/img/ganesh.jpg";

// const inter = Inter({ subsets: [ "latin" ] });
export const getStaticProps = async () => {
  const res = await fetch("http://127.0.0.1:8000/post/latest", { method: "POST" });
  const data = await res.json();
  return { props: { posts: data }, revalidate: 40 };
};

export default function Home({ posts }) {
  const { data: session } = useSession();
  useEffect(() => {
    if (session?.error == "RefreshAccessTokenError") {
      signIn();
    }
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/logos/k_favicon.ico" />
      </Head>
      <Header image={Ganesh}>
        <h1 className="[font-size:_3rem] lg:[font-size:5rem]">Art blog</h1>
        <h2 className="sub-heading">Dream Blog for Artists</h2>
      </Header>
      <main className="mb-12">
        <div className="mx-auto flex flex-col justify-center !px-10 lg:!px-12">
          {/* centering the post */}

          {/* eslint-disable-next-line tailwindcss/no-custom-classname */}
          {posts.map((post) => (
            <>
              <div className="container mx-auto my-6 rounded-md bg-white px-4 py-8 shadow-zinc-500 drop-shadow-2xl">
                {/* Post preview */}
                <Link
                  href={`/${post.author.username}/${post.slug}`}
                  className="text-gray-900"
                >
                  <h2 className="mt-[1.875rem] mb-[0.625rem] text-4xl font-extrabold [line-height:1.2]">
                    {post.title}
                  </h2>
                  <h3 className="mb-[0.625rem] text-[calc(1.3rem_+_.6vw)] font-[300] xl:text-[1.75rem] ">
                    {post.sub_title ? post.sub_title : post.content[20]}
                  </h3>
                </Link>
                <p className="m-[2rem_0] mt-0 mb-4 text-[1.125rem] italic text-slate-600">
                  Posted by{" "}
                  <Link href={`${post.author.username}`}>{post.author.FullName}</Link> on{" "}
                  {post.creation_time}
                </p>
              </div>
            </>
          ))}

          <div className=" container rounded-md bg-white px-4 py-8 shadow-zinc-500 drop-shadow-2xl">
            {/* Post preview */}
            <Link href="/" className="text-gray-900">
              <h2 className=" text-4xl font-extrabold [line-height:1.2]">
                Man must explore, and this is exploration at its greatest
              </h2>
              <h3 className="mb-[0.625rem] text-[calc(1.3rem_+_.6vw)] font-[300] xl:text-[1.75rem] ">
                Problems look mighty small from 150 miles up
              </h3>
            </Link>
            <p className="m-[2rem_0] mt-0 mb-4 text-[1.125rem] italic text-slate-600">
              Posted by <Link href="/">Start Bootstrap</Link> on March 5, 2023
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
