import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import Link from "next/link";

// import image
import Ganesh from "../static/img/ganesh.jpg";

const inter = Inter({ subsets: [ "latin" ] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/logos/k_favicon.ico" />
      </Head>
      <Header image={ Ganesh }>
        <h1 className="[font-size:_3rem] lg:[font-size:5rem]">Art blog</h1>
        <h2 className="sub-heading">Dream Blog for Artists</h2>
      </Header>
      <main className="mb-12">
        <div className="container mx-auto !px-6 lg:!px-12">
          {/* centering the post */ }
          <div className="row justify-center [--bs-gutter-x:1.5rem] lg:[--bs-gutter-x:3rem]">
            <div className="flex-[0_0_auto] rounded-lg bg-gray-50 shadow-gray-400 drop-shadow-2xl md:w-[83.33333333%] lg:w-[66.66666667%] xl:w-[58.33333333%]">
              <div className="post-preview">
                {/* Post preview */ }
                <Link href="/" className="text-gray-900">
                  <h2 className="mt-[1.875rem] mb-[0.625rem] text-4xl font-extrabold [line-height:1.2]">
                    Man must explore, and this is exploration at its greatest
                  </h2>
                  <h3 className="mb-[0.625rem] text-[calc(1.3rem_+_.6vw)] font-[300] xl:text-[1.75rem] ">
                    Problems look mighty small from 150 miles up
                  </h3>
                </Link>
                <p className="m-[2rem_0] mt-0 mb-4 text-[1.125rem] italic text-slate-600">
                  Posted by <a href="/">Start Bootstrap</a> on March 5, 2023
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
